#!/usr/bin/env bash
# This script prints numbers 1 to 100 with Fizz, Buzz, and FizzBuzz replacements

for i in {1..100}
do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done
