#!/usr/bin/env bash
# This script reads /etc/passwd and displays specific user details line by line

# shellcheck disable=SC2034
while IFS=: read -r username password uid gid info home shell
do
    echo "$username:$uid:$home"
done < /etc/passwd
