#!/bin/bash
python3 -c "w=int('$WATER'.translate(str.maketrans('water','01234')),5);s=int('$STIR'.translate(str.maketrans('stir','0123')),4);print(('{:o}'.format(w+s)).translate(str.maketrans('01234567','bestchol')))"
